name: cosmetics
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  animate_do: ^4.2.0
  carousel_slider: ^5.1.2
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  dropdown_button2: ^3.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.2
  logger: ^2.7.0
  maps_launcher: ^3.0.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/cairo/

  fonts:
    - family: "Cairo"
      fonts:
        - asset: assets/fonts/cairo/black.ttf
          weight: 200
        - asset: assets/fonts/cairo/light.ttf
          weight: 300
        - asset: assets/fonts/cairo/regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/cairo/bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/extra_bold.ttf
          weight: 800
        - asset: assets/fonts/cairo/black.ttf
          weight: 900
